### ISSUE TITLE
[bug]: irregular charge state indication

### ISSUE THREAD

**Issue by cosmos1721** [ashish-kus/batfetch#2]
PFA shows the issue, it should show 'connected and Charging'. instead only last values are changing.
![image](https://github.com/ashish-kus/batfetch/assets/91248142/bcf300da-7c8c-45c6-8d83-d91066e8615e)

**Comment by ashish-kus** [comment]
I have successfully fixed the bug. The issue has been resolved and the fix is available in the latest commit. 
 Thank you for your contribution.
