### ISSUE TITLE
Not readable on black-on-white terminal. Suggestion: Add a no-colouring option and other colour schemes.

### ISSUE THREAD

**Issue by dreirund** [ashish-kus/batfetch#3]
I use a black on white terminal colour scheme.

In this, some information is not readable, some barely.

Solution suggestion: When you use colouring, adapt to the terminal colour scheme, or allow the user to select a colour scheme (via config file/ command line option), and maybe default to no colouring (making it compatible over dump terminals by default).

Screenshot attached.

Regards!

---
![Screenshot of 'batfetch' in a black-on-white terminal](https://github.com/ashish-kus/batfetch/assets/1590519/21425764-3255-44a1-a7d6-4a96472866cb "batfetch_in_white_terminal.png")

---
*(The gray parts are where I have censored private information.  
`model` has no entry on my machine. But `<user@host>` is not shown (white on white), and overall bright colours on white background are barely readable.)*

**Comment by dreirund** [comment]
As a suggestion, `tput`  from `terminfo` (instead of `printf`) might be a way to at least have terminal-sensitive formatting.

**Comment by ashish-kus** [comment]
Resolved by creating a config file for managing color variables. Limited to three colors (BF_COL1=2, BF_COL2=7, BF_COL3=6), the terminal now displays a bold message signifying the successful fix with an elegant layout of battery information. 

Thanks for your patience and support!

**Comment by dreirund** [comment]
> ***ashish-kus** closed this as completed 11 hours ago*

:pray:

**Comment by ashish-kus** [comment]
I have tackled another request you made. Now, a "No-Colored Output" option is available. When selected, the default terminal scheme's foreground color ensures clear readability.

Thanks for your contribution.
