### ISSUE TITLE
Trying to get batfetch output into an eww widget:

### ISSUE THREAD

**Issue by xircon** [ashish-kus/batfetch#6]
Would it be possible to have an option to not have the ANSI escape sequences?  Just print the info below the graphic?

eww is Elkowars Wacky Widgets.

**Comment by ashish-kus** [comment]
Hey there, thanks for the feedback!

While I'm new to Eww widgets, I'm eager to help.  JSON output for skipping ASCII art sound useful? I can add a flag to enable it.  Let me know!

**Comment by xircon** [comment]
Brilliant, would work perfectly!  Thank you for such a good utility!!

**Comment by ashish-kus** [comment]
@xircon Thank you for your feedback. I'm pleased to inform you that the latest update includes a new JSON output flag, addressing the  issue. 
use ``` batfetch --json ```

 Your input is valuable, and I appreciate your use of BatFetch.

**Comment by xircon** [comment]
![2024-01-07T19:42:27,318801231+00:00](https://github.com/ashish-kus/batfetch/assets/1316691/b69674c7-2b27-4ef9-af1e-c076e73935f4)

Thanks works perfectly :smile:
